config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/home', to: 'static_pages#home'
  get '/sign_on', to: 'static_pages#sign_on'
  get '/about', to: 'static_pages#about_us'

  resources :routes, only: [:index, :show]
  resources :trains, only: [:show]
  resources :users, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :routes, only: [:index, :show] do
        resources :trains, only: [:index]
        resources :stations, only: [:index]
      end

      resources :stations, only: [] do
        resources :trains, only: [] do
          resources :train_stops, only: [:index]
        end
      end

      resources :users, only: [:index, :show] do
        resources :trains, only: []
        resources :stations, only: []
        resources :routes, only: []
        collection do
          get 'current_user_id'
          get 'toggle_favorite_route'
          get 'toggle_favorite_train'
          get 'toggle_favorite_station'
        end
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"
  get '*path', to: 'static_pages#error'
end

app/models/Calendar.rb
class Calendar < ApplicationRecord
  validates :feed_id, :service_id, :start_date, :end_date, presence: true
  validates :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, presence: true
end

app/models/agency.rb
class Agency < ApplicationRecord
  self.primary_key = "agency_id"

  validates :feed_id, :agency_id, :agency_name, :agency_url, :agency_timezone, presence: true
end

app/models/calendar_date.rb
class CalendarDate < ApplicationRecord
  validates :feed_id, :service_id, :date, :exception_type, presence: true
end

app/models/fare_attribute.rb
class FareAttribute < ApplicationRecord
  validates :feed_id, :fare_id, :price, :currency_type, :payment_method, :transfers, presence: true
end

app/models/fare_rule.rb
class FareRule < ApplicationRecord
  validates :feed_id, :fare_id, presence: true
end

app/models/feed.rb
class Feed < ApplicationRecord
  validates :feed_publisher_name, :feed_publisher_url, :feed_lang, presence: true
  validate :feed_date_range

  private

  def feed_date_range
    # ensure feed_start_date < feed_end_date
  end
end

app/models/frequency.rb
class Frequency < ApplicationRecord
  validates :feed_id, :trip_id, :start_time, :end_time, :headway_secs, :exact_times, presence: true
end

app/models/gtfs.rb
require 'gtfs/version'
require 'gtfs/model'
require 'gtfs/agency'
require 'gtfs/calendar'
require 'gtfs/calendar_date'
require 'gtfs/feed_info'
require 'gtfs/route'
require 'gtfs/shape'
require 'gtfs/stop'
require 'gtfs/stop_time'
require 'gtfs/trip'
require 'gtfs/custom_exceptions'
require 'gtfs/fare_attribute'
require 'gtfs/fare_rule'
require 'gtfs/frequency'
require 'gtfs/transfer'

require 'gtfs/source'
require 'gtfs/url_source'
require 'gtfs/local_source'

app/models/route.rb
class Route < ApplicationRecord
  self.primary_key = "route_id"

  validates :feed_id, :route_id, :route_type, presence: true
  validates :route_short_name, length: { in: 0..255, allow_nil: false }
  validates :route_long_name, length: { in: 0..255, allow_nil: false }
  validate :name_is_present

  private

  def name_is_present
    if self.route_short_name.empty? && self.route_long_name.empty?
      self.errors.add :base, 'Route must have a name'
    end
  end
end

app/models/shape.rb
class Shape < ApplicationRecord
  validates :feed_id, :shape_id, :shape_pt_lat, :shape_pt_lon, :shape_pt_sequence, presence: true
end

app/models/stop.rb
class Stop < ApplicationRecord
  validates :feed_id, :stop_id, :stop_name, :stop_lat, :stop_lon, presence: true
end

app/models/stop_time.rb
class StopTime < ApplicationRecord
  validates :feed_id, :trip_id, :stop_id, :stop_sequence, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
  validates :train_num, :route_id, presence: true
  validates :train_num, uniqueness: true
  validates :inbound, inclusion: { in: [true, false] }

  belongs_to :route
  has_many :train_stops
  has_many :stations, through: :train_stops
  # has_many :user_favorite_trains
  # has_many :users, through: :user_favorite_trains
end

app/models/train_stop.rb
class TrainStop < ApplicationRecord
  validates :train_id, presence: true
  validates :station_id, presence: true

  belongs_to :train
  belongs_to :station
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  validates :feed_id, :from_stop_id, :to_stop_id, :transfer_type, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :feed_id, :route_id, :service_id, :trip_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :provider, :uid, :username, :name, :email, presence: true
  validate :phone_number_must_be_valid

  has_many :user_favorite_routes
  has_many :user_favorite_trains
  has_many :user_favorite_stations

  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.provider = provider
      user.uid = uid
      user.email = auth.info.email
      user.username = auth.info.nickname ? auth.info.nickname : auth.info.name
      user.avatar_url = auth.info.image
      user.name = auth.info.name
    end
  end

  private

  def phone_number_must_be_valid
    unless self.phone_number.nil?
      if self.phone_number.length != 10
        errors.add(:phone_number, "must be 10 digits.")
      end

      if self.phone_number.to_i.length != 10
        errors.add(:phone_number, "may only include numbers.")
      end
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Train Spotter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans|PT+Serif" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="row full-width text-align-center">
      <div class="small-4 medium-2 columns header-nav">
        <span><a href="/"><%= image_tag 'logo.png', class: "logo", href: "/" %></a></span>
      </div>
      <div class="small-0 medium-6 columns title-nav"><h1 class="title">Train Spotter</h1><h4 class="sub-title">An organized view of Boston's unorganized transportation system</h4></div>

      <div class="small-4 medium-2 columns user-nav">
        <div class="dropdown nav-menu">
          <span>
            <div class="menu-container" onclick="myFunction(this)">
              <div class="bar1"></div>
              <div class="bar2"></div>
              <div class="bar3"></div>
            </div>
          </span>
          <div class="dropdown-content">
            <%= link_to 'Home', root_path, class: "button sign-on-button" %>
            <%= link_to 'About Us', about_path, class: "button sign-on-button"%>
            <div className="divider"> </div>
            <% if current_user %>
              <%= link_to current_user.name, user_path(current_user.id), class: "button sign-on-button" %>
              <%= link_to 'Logout', logout_path, method: 'delete', class: "button sign-on-button" %>
            <% else %>
              <div className="container">
                <h4 class="user-nav-text button sign-on-button">Log In</h4>
                <div className="user-nav-buttons">
                  <%= link_to 'Facebook', "/auth/facebook", class: "button sign-on-button" %>
                  <%= link_to 'Github', "/auth/github", class: "button sign-on-button" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <div id="body">
      <div id="rails-app">
      <%= yield %>
      </div>
      <div id='react-app'>
      </div>
    </div>

  </body>
</html>